name: my_domain_bridge
from_domain: 0
to_domain: 4

topics:
  # Bridge "/foo/chatter" topic from doman ID 2 to domain ID 3
  # Automatically detect QoS settings and default to 'keep_last' history with depth 1

  /changi/cloud_inW:
    type: sensor_msgs/msg/PointCloud2
  /changi/detected_interest_points:
    type: sensor_msgs/msg/PointCloud2
  /changi/gimbal:
    type: geometry_msgs/msg/TwistStamped
  /changi/ground_truth/odometry:
    type: nav_msgs/msg/Odometry
  /changi/nbr_kf_cloud:
    type: sensor_msgs/msg/PointCloud2
  /changi/nbr_odom_cloud:
    type: sensor_msgs/msg/PointCloud2
  /changi/slf_kf_cloud:
    type: sensor_msgs/msg/PointCloud2

  /domain4/gcs/bounding_box_vertices:
    type: sensor_msgs/msg/PointCloud
    remap: gcs/bounding_box_vertices

  /domain4/jurong/cloud_inW:
    type: sensor_msgs/msg/PointCloud2
    remap: jurong/cloud_inW
  /domain4/jurong/detected_interest_points:
    type: sensor_msgs/msg/PointCloud2
    remap: jurong/detected_interest_points
  /domain4/jurong/gimbal:
    type: geometry_msgs/msg/TwistStamped
    remap: jurong/gimbal
  /domain4/jurong/ground_truth/odometry:
    type: nav_msgs/msg/Odometry
    remap: jurong/ground_truth/odometry
  /domain4/jurong/nbr_kf_cloud:
    type: sensor_msgs/msg/PointCloud2
    remap: jurong/nbr_kf_cloud
  /domain4/jurong/nbr_odom_cloud:
    type: sensor_msgs/msg/PointCloud2
    remap: jurong/nbr_odom_cloud
  /domain4/jurong/slf_kf_cloud:
    type: sensor_msgs/msg/PointCloud2
    remap: jurong/slf_kf_cloud

  /domain4/nanyang/cloud_inW:
    type: sensor_msgs/msg/PointCloud2
    remap: nanyang/cloud_inW
  /domain4/nanyang/detected_interest_points:
    type: sensor_msgs/msg/PointCloud2
    remap: nanyang/detected_interest_points
  /domain4/nanyang/gimbal:
    type: geometry_msgs/msg/TwistStamped
    remap: nanyang/gimbal
  /domain4/nanyang/ground_truth/odometry:
    type: nav_msgs/msg/Odometry
    remap: nanyang/ground_truth/odometry
  /domain4/nanyang/nbr_kf_cloud:
    type: sensor_msgs/msg/PointCloud2
    remap: nanyang/nbr_kf_cloud
  /domain4/nanyang/nbr_odom_cloud:
    type: sensor_msgs/msg/PointCloud2
    remap: nanyang/nbr_odom_cloud
  /domain4/nanyang/slf_kf_cloud:
    type: sensor_msgs/msg/PointCloud2
    remap: nanyang/slf_kf_cloud

  /domain4/raffles/cloud_inW:
    type: sensor_msgs/msg/PointCloud2
    remap: raffles/cloud_inW
  /domain4/raffles/detected_interest_points:
    type: sensor_msgs/msg/PointCloud2
    remap: raffles/detected_interest_points
  /domain4/raffles/gimbal:
    type: geometry_msgs/msg/TwistStamped
    remap: raffles/gimbal
  /domain4/raffles/ground_truth/odometry:
    type: nav_msgs/msg/Odometry
    remap: raffles/ground_truth/odometry
  /domain4/raffles/nbr_kf_cloud:
    type: sensor_msgs/msg/PointCloud2
    remap: raffles/nbr_kf_cloud
  /domain4/raffles/nbr_odom_cloud:
    type: sensor_msgs/msg/PointCloud2
    remap: raffles/nbr_odom_cloud
  /domain4/raffles/slf_kf_cloud:
    type: sensor_msgs/msg/PointCloud2
    remap: raffles/slf_kf_cloud

  /domain4/sentosa/cloud_inW:
    type: sensor_msgs/msg/PointCloud2
    remap: sentosa/cloud_inW
  /domain4/sentosa/detected_interest_points:
    type: sensor_msgs/msg/PointCloud2
    remap: sentosa/detected_interest_points
  /domain4/sentosa/gimbal:
    type: geometry_msgs/msg/TwistStamped
    remap: sentosa/gimbal
  /domain4/sentosa/ground_truth/odometry:
    type: nav_msgs/msg/Odometry
    remap: sentosa/ground_truth/odometry
  /domain4/sentosa/nbr_kf_cloud:
    type: sensor_msgs/msg/PointCloud2
    remap: sentosa/nbr_kf_cloud
  /domain4/sentosa/nbr_odom_cloud:
    type: sensor_msgs/msg/PointCloud2
    remap: sentosa/nbr_odom_cloud
  /domain4/sentosa/slf_kf_cloud:
    type: sensor_msgs/msg/PointCloud2
    remap: sentosa/slf_kf_cloud

  # Command
  /changi/command/gimbal:
    type: geometry_msgs/msg/Twist
    from_domain: 4
    to_domain: 0
  /changi/command/trajectory:
    type: trajectory_msgs/msg/MultiDOFJointTrajectory
    from_domain: 4
    to_domain: 0

  # Bridge "/clock" topic from doman ID 2 to domain ID 3,
  # Override durability to be 'volatile' and override depth to be 1
  clock:
    type: rosgraph_msgs/msg/Clock
    qos:
      durability: volatile
      depth: 1

  # Bridge "/clock" topic from doman ID 2 to domain ID 6
  # Automatically detect QoS settings and override history to 'keep_all'
  # clock:
  #   type: rosgraph_msgs/msg/Clock
  #   to_domain: 6
  #   qos:
  #     history: keep_all

  # Bridge "/chitter" topic from domain ID 2 to domain ID 3 with the name "/chatter"
  # chitter:
  #   type: example_interfaces/msg/String
  #   remap: chatter

# services:
  # Bridge "add_two_ints" service from domain ID 4 to domain ID 6
  # add_two_ints:
  #   type: example_interfaces/srv/AddTwoInts
  #   from_domain: 4
  #   to_domain: 6

# actions:
  # Bridge "fibonacci" action from domain ID 1 to domain ID 3
  # fibonacci:
  #   type: example_interfaces/action/Fibonacci
  #   from_domain: 1